### ISSUE TITLE
Encoding Problems in Column "Task"

### ISSUE THREAD

**Issue by winterbe** [pbauerochse/youtrack-worklog-viewer#1]
Awesome Tool Patrick! :+1: 

I'm encountering encoding problems in the first column *Task*. Instead of german umlauts the tool displays a question mark.

Another minor issue: First column *Task* is hardly readable on Mac OSX when row is selected (blue text on blue background).

**Comment by pbauerochse** [comment]
Unfortunately I can't fix the encoding issues in the first column. The data is already corrupt in the csv file (see Youtrack issue https://youtrack.jetbrains.com/issue/JT-29234)

As for the readability of the first column: I'll see what I can do ;)

**Comment by pbauerochse** [comment]
Highlighting fixed with release 1.1.1: https://github.com/pbauerochse/youtrack-worklog-viewer/releases/tag/v1.1.1
