### ISSUE TITLE
Support for YouTrack 6.5

### ISSUE THREAD

**Issue by denis-bogdanas** [pbauerochse/youtrack-worklog-viewer#12]
Unfortunately in Youtrack 6.5 the authentication mode was changed: https://confluence.jetbrains.com/display/YTD65/Log+in+to+YouTrack

Could you please implement the new auth method? I'm very interested to use this tool.

thank you,
Denis

**Comment by pbauerochse** [comment]
Hi Denis,

I'll see what I can do

**Comment by pbauerochse** [comment]
Hi Denis,

I think I got it working. Please check out the new version and ask your YouTrack administrator to setup a service for you as described here https://github.com/pbauerochse/youtrack-worklog-viewer#setting-up-oauth2

Let me know if that works for you.

Cheers

Patrick

**Comment by denis-bogdanas** [comment]
Ok, will check in a few days and let you know.

**Comment by denis-bogdanas** [comment]
Hi,
Unfortunately I don't see any of the menus that you screenshotted. This is the menu I have:

![settings menu](https://github-cloud.s3.amazonaws.com/assets/5214914/10566208/2d4a9506-7595-11e5-97e3-2bb34a88924a.png)

and the "hub integration page":

![hub integration](https://github-cloud.s3.amazonaws.com/assets/5214914/10566211/3d24681c-7595-11e5-99a1-424cff1d78d9.png)

The URL for this page is http://proj-name.myjetbrains.com/youtrack/ring

thank you,
Denis


 I'm using the free in-cloud version of youtrack.

**Comment by pbauerochse** [comment]
Hi Denis,

your Hub URL would be http://proj-name.myjetbrains.com/hub

The "Hub integration page" shown in your screenshots got me confused too the first time ;) Try the above link and follow the instruction. This should work.

Let me know.

Cheers

Patrick

**Comment by denis-bogdanas** [comment]
I tried it. I got error 404:
![hub page](https://cloud.githubusercontent.com/assets/5214914/10585089/a64e0d92-764a-11e5-8452-577a01599657.png)

**Comment by pbauerochse** [comment]
it's https://java-semantics.myjetbrains.com/hub not https://java-semantics.myjetbrains.com/youtrack/hub :) You also need to be administrator of your youtrack instance to get onto that page.

**Comment by denis-bogdanas** [comment]
On 19 October 2015 at 11:04, pbauerochse <notifications@github.com> wrote:

> https://java-semantics.myjetbrains.com/hub n


Hi,
The URL you proposed redirects me to the dashboard. And I am administrator.
It's a one-man issue tracker.

-- 
Denis

**Comment by pbauerochse** [comment]
Hi Denis,

I'm not sure why this is happening. I just signed up for the free online youtrack and I can access the hub. Maybe it is because I still have the 30 day trial left. I'm afraid I can not test this until my 30 days trial has expired :(

**Comment by denis-bogdanas** [comment]
Hi,
thank you for all the effort!

You have to go to https://account.jetbrains.com/licenses 
Click on "change plan" for your test youtrack instance, and select the free plan.

**Comment by pbauerochse** [comment]
Hi Denis,

I "upgraded" my plan to the free 10 user plan and still can access the hub page. I also am able to use the worklog viewer using the regular rest login. I'm still not sure why it's not working with your instance.

Maybe the REST API works with your youtrack instance but you entered the wrong credentials? You need to set the username **exactly** as it is shown in youtrack in your profile section. That was a common error when setting up the worklog viewer in my company.

Could you paste the error message or part from the log when you try to access rest api? The log is available under "Help -> Log Messages".

**Comment by denis-bogdanas** [comment]
Hi, for that I have to access the Hub page first:) I'll create a new youtrack server and will see whether I can do it from there.

**Comment by denis-bogdanas** [comment]
Hi, I figured out in the end how to access hub page. The protocol should be http, not https. If I use https, the url is redirected to dashboard.

So I followed your tutorial, and now I get a NPE on worklog viewer startup:

java.lang.NullPointerException: null
	at jetbrains.jetpass.client.oauth2.SimpleTokenLoader.loadAccessToken(SimpleTokenLoader.java:55) ~[client-1.0.41.jar:na]

I've set a test youtrack instance to make our life simpler:

url: http://worklog-test.myjetbrains.com
user: root
password: root
oauth id: 926ef3d1-602b-45c2-a13d-e289af01518e
oauth secret: wZ7bD8JVU4T4

Could you please check?

**Comment by pbauerochse** [comment]
Allright Denis, I think I got it. I made wrong assumptions about the Hub path when being hosted at Jetbrains.

For the hosted acounts the url of YouTrack is http://mycompany.myjetbrains.com/youtrack while the Hub URL is http://mycompany.myjetbrains.com/hub. But the WorklogViewer assumed the URL would be http://mycompany.myjetbrains.com/youtrack/hub therefore it wouldn't work.

I fixed the URL generation and also allowed setting the YouTrack URL and the Hub URL separately in the settings dialogue.

Please download the newest version from [here](https://github.com/pbauerochse/youtrack-worklog-viewer/releases/tag/2.1.1) and open the settings dialogue. It should then already update the Hub URL properly. Save your settings and then try again.

Testing with your example host I got http://worklog-test.myjetbrains.com/youtrack for the Youtrack-URL and http://worklog-test.myjetbrains.com/hub for the Hub-URL and then everything works fine.

Let me know if this works for you. If everything works fine on your end I will remove all sensitive information from this conversation ;)

Keeping my fingers crossed

Cheers

Patrick

**Comment by denis-bogdanas** [comment]
Everything works fine, thank you a lot!

Btw, you don't have to delete anything. I will delete this test instance a bit later.
