### ISSUE TITLE
Support for Saturday and Sunday

### ISSUE THREAD

**Issue by denis-bogdanas** [pbauerochse/youtrack-worklog-viewer#14]
Hi Patrick,
Could you please add support for Saturday and Sunday? For example 2 checkboxes in the settings, one for each day, that would prevent collapsing the weekend days in the table.

Alternatively, I tried to extend weekend day columns from the table, but column headers seem disconnected from the column body, the body does not extend:

![screenshot](https://cloud.githubusercontent.com/assets/5214914/10682213/6fd8f138-78e7-11e5-998b-a31665a4acb7.png)

**Comment by pbauerochse** [comment]
Hi Denis,

I guess this will be an easy one compared to the OAuth thing ;) I'll get into it soon.

Cheers

Patrick

**Comment by denis-bogdanas** [comment]
It works now, thanks!
