### ISSUE TITLE
Custom range does not work

### ISSUE THREAD

**Issue by denis-bogdanas** [pbauerochse/youtrack-worklog-viewer#16]
Attempt to fetch the tasks with custom range throws an exception:

java.lang.IllegalStateException: Could not create temporary report (Message: Bad Request, StatusCode: 400)
Context:
- grouping: none
- youtrack instance: incloud v6.5

Reports with predefined ranges work.

Could you please look into it?

**Comment by pbauerochse** [comment]
Hi Denis,

this issue should be resolved with the latest version. YouTrack does not allow creating a report with a slash (/) contained in the name. I assume that you are on a system where the U.S. date format is being used as a locale. Could you please try again with version 2.2.1 and let me know if it works?

Cheers

Patrick

**Comment by denis-bogdanas** [comment]
It works now, thanks!

Denis
