### ISSUE TITLE
Unexpected YouTrack response status code (Message: Not Found, StatusCode: 404)

### ISSUE THREAD

**Issue by pawstern95** [pbauerochse/youtrack-worklog-viewer#25]
I`m getting 404 error when I create reports. 
YouTrack 2018.1.39916

> 13:51:44.410 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task GetGroupByCategories-Task changed from READY to SCHEDULED
13:51:44.410 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task GetGroupByCategories-Task changed from SCHEDULED to RUNNING
13:51:44.531 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task GetGroupByCategories-Task changed from RUNNING to SUCCEEDED
13:51:44.531 [JavaFX Application Thread] INFO  d.p.w.fx.MainViewController - Task GetGroupByCategories-Task succeeded
13:51:44.531 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Delegating Event to previous onSucceeded event handler
13:51:44.531 [JavaFX Application Thread] INFO  d.p.w.fx.MainViewController - GetGroupByCategories-Task succeeded with 17 GroupByCategories
13:51:44.535 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task VersionChecker-Task changed from READY to SCHEDULED
13:51:44.535 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task VersionChecker-Task changed from SCHEDULED to RUNNING
13:51:45.158 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task VersionChecker-Task changed from RUNNING to SUCCEEDED
13:51:45.159 [JavaFX Application Thread] INFO  d.p.w.fx.MainViewController - Task VersionChecker-Task succeeded
13:51:45.159 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Delegating Event to previous onSucceeded event handler
13:51:45.160 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Most recent github version is 2.3.0, this version is 2.3.0
13:51:46.704 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Fetch worklogs clicked for timerange THIS_MONTH
13:51:46.705 [JavaFX Application Thread] INFO  d.p.w.d.t.TimerangeProviderFactory - Using timerange provider class class de.pbauerochse.worklogviewer.domain.timerangeprovider.CurrentMonthTimerangeProvider
13:51:46.705 [JavaFX Application Thread] INFO  d.p.w.fx.MainViewController - Starting task FetchTimereport-Task
13:51:46.706 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task FetchTimereport-Task changed from READY to SCHEDULED
13:51:46.706 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task FetchTimereport-Task changed from SCHEDULED to RUNNING
13:51:46.706 [pool-2-thread-1] DEBUG d.p.w.y.v20174.YouTrackServiceV20174 - Creating temporary timereport using url https://youtrack.blastlab.tech/api/reports?fields=$type,authors(fullName,id,login,ringId),effectiveQuery,effectiveQueryUrl,id,invalidationInterval,name,own,owner(id,login),pinned,projects(id,name,shortName),query,sprint(id,name),status(calculationInProgress,error(id),errorMessage,isOutdated,lastCalculated,progress,wikifiedErrorMessage),visibleTo(id,name),wikifiedError,windowSize,workTypes(id,name)
13:51:47.777 [pool-2-thread-1] DEBUG d.p.w.y.v20174.YouTrackServiceV20174 - Fetching report details for report 102-1480 using url https://youtrack.blastlab.tech/api/reports/102-1480/status?fields=calculationInProgress,error(id),errorMessage,isOutdated,lastCalculated,progress,wikifiedErrorMessage
13:51:47.829 [pool-2-thread-1] DEBUG d.p.w.y.v20174.YouTrackServiceV20174 - Received JSON response {"lastCalculated":1520254397941,"errorMessage":null,"progress":-1,"error":null,"wikifiedErrorMessage":"","isOutdated":false,"calculationInProgress":false,"$type":"jetbrains.charisma.smartui.report.ReportStatus"}
13:51:47.830 [pool-2-thread-1] DEBUG d.p.w.y.v20174.YouTrackServiceV20174 - Downloading report 102-1480 using url https://youtrack.blastlab.tech/api/reports/102-1480/export
13:51:47.865 [pool-2-thread-1] DEBUG d.p.w.y.v20174.YouTrackServiceV20174 - Deleting report 102-1480 using url https://youtrack.blastlab.tech/api/reports/102-1480?fields=$type,authors(fullName,id,login,ringId),effectiveQuery,effectiveQueryUrl,id,invalidationInterval,name,own,owner(id,login),pinned,projects(id,name,shortName),query,sprint(id,name),status(calculationInProgress,error(id),errorMessage,isOutdated,lastCalculated,progress,wikifiedErrorMessage),visibleTo(id,name),wikifiedError,windowSize,workTypes(id,name)
13:51:47.913 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Task FetchTimereport-Task changed from RUNNING to FAILED
13:51:47.913 [JavaFX Application Thread] WARN  d.p.w.fx.MainViewController - Task FetchTimereport-Task failed
13:51:47.918 [JavaFX Application Thread] WARN  d.p.w.fx.MainViewController - Showing error to user
java.lang.IllegalStateException: Unexpected YouTrack response status code (Message: Not Found, StatusCode: 404)
	at de.pbauerochse.worklogviewer.util.ExceptionUtil.getIllegalStateException(ExceptionUtil.java:34) ~[youtrack-worklog-viewer-2.3.0.jar:na]
	at de.pbauerochse.worklogviewer.util.ExceptionUtil.getIllegalStateException(ExceptionUtil.java:30) ~[youtrack-worklog-viewer-2.3.0.jar:na]
	at de.pbauerochse.worklogviewer.youtrack.v20174.YouTrackServiceV20174.lambda$downloadReport$0(YouTrackServiceV20174.java:198) ~[youtrack-worklog-viewer-2.3.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222) ~[youtrack-worklog-viewer-2.3.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164) ~[youtrack-worklog-viewer-2.3.0.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139) ~[youtrack-worklog-viewer-2.3.0.jar:na]
	at de.pbauerochse.worklogviewer.youtrack.v20174.YouTrackServiceV20174.downloadReport(YouTrackServiceV20174.java:186) ~[youtrack-worklog-viewer-2.3.0.jar:na]
	at de.pbauerochse.worklogviewer.fx.tasks.FetchTimereportTask.call(FetchTimereportTask.java:68) ~[youtrack-worklog-viewer-2.3.0.jar:na]
	at de.pbauerochse.worklogviewer.fx.tasks.FetchTimereportTask.call(FetchTimereportTask.java:20) ~[youtrack-worklog-viewer-2.3.0.jar:na]
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423) ~[jfxrt.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_161]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_161]
13:51:49.950 [JavaFX Application Thread] DEBUG d.p.w.fx.MainViewController - Showing log messages dialogue
13:51:49.964 [JavaFX Application Thread] DEBUG d.p.w.fx.LogViewController - Initializing
13:51:49.969 [JavaFX Application Thread] DEBUG d.p.w.fx.LogViewController - Adding WindowChangeListener

**Comment by pbauerochse** [comment]
Darn..once again YouTrack changed the request mappings. I'll have to see into it..Will look into it next week.

**Comment by pbauerochse** [comment]
@pawstern95 a new version has just been released..after downloading the new version please go to the settings dialog and set the youtrack version to "2018.1 or newer"

Cheers
