### ISSUE TITLE
Dislocated work times

### ISSUE THREAD

**Issue by mingalll** [pbauerochse/youtrack-worklog-viewer#26]
When I generate a report, the work time for each issue is dislocated to the previous day. What was done on Monday(Seg 28.05.) is displayed on Sunday(Dom 27.05.) and so on.
![dsbuffer bmp](https://user-images.githubusercontent.com/14894874/40981843-5da9306e-68b2-11e8-9b37-a9274e0886f2.png)

**Comment by pbauerochse** [comment]
Might I ask what time zone you are located in? That might give me an indication what is going on. I will look into it.

**Comment by mingalll** [comment]
GMT-3, São Paulo

**Comment by pbauerochse** [comment]
I can successfully reproduce the issue and will start working on a fix. I will get back to you as soon as I have a solution. Hold tight ;)

**Comment by pbauerochse** [comment]
Hi @mingalll ,

I just published a release at https://github.com/pbauerochse/youtrack-worklog-viewer/releases/tag/2.3.4

Could you please try and see if this resolves your issue? Let me know.

Cheers

**Comment by pbauerochse** [comment]
Perfect! Enjoy!
