### ISSUE TITLE
Overtime overview for selected timerange

### ISSUE THREAD

**Issue by rotrotrotrot** [pbauerochse/youtrack-worklog-viewer#37]
I'd like to have an overview of overtime hours spent on a selected timerange.
This time should be summed over workdays with logged time only.
The "Work hours per day" setting should be used to calculate the desired amount of time I should have worked.
In future an integration into a vacation management system would be nice, but for the moment vacations and legal holidays must not be considered.
I think the statistics sidebar would be a good location to display the overtime hours.

**Comment by pbauerochse** [comment]
Will soon be released with 2.6.1
