### ISSUE TITLE
Error when clicking "Download Worklogs"

### ISSUE THREAD

**Issue by DustRaven** [pbauerochse/youtrack-worklog-viewer#39]
I'm getting the following error: 

> Cannot construct instance of 'de.pbauerochse.worklogviewer.connector.v2019.model.YouTrackCustomFieldValue' (although at least one Creator exists): no int/int-argument constructor/factory method to deserialize from Number value (2) at [Source: (String)"2": line 1, column: 1]

I'm using the AdoptOpenJDK 11.0.4.11-hotspot.

**Comment by manne01** [comment]
Same here with YouTrack 2019.2 Build 6111 and AdoptOpenJDK.

**Comment by pbauerochse** [comment]
I'll look into it. It seems that your YouTrack instance has a custom field in a form that I did not consider.

**Comment by pbauerochse** [comment]
Nevermind. I think I figured out what's going on. @manne01 @DustRaven could you try again with version 2.6.1 please?

https://github.com/pbauerochse/youtrack-worklog-viewer/releases/tag/2.6.1

**Comment by manne01** [comment]
Thank you so much, it's working again!

**Comment by pbauerochse** [comment]
Glad to hear that. I'll close this issue then. Feel free to reopen, if the issue surfaces again
