### ISSUE TITLE
id for own user: not found 

### ISSUE THREAD

**Issue by batihu** [pbauerochse/youtrack-worklog-viewer#44]
bug:
when I save a new work item I got an error 
![image](https://github.com/pbauerochse/youtrack-worklog-viewer/assets/12643174/3bfb7309-7fa3-459d-8732-a3f74384707d)

repro:
doubleclick on a row in table own worklogs 
fill the fields
press save button

**Comment by adolfo-novo** [comment]
Same here...

**Comment by pbauerochse** [comment]
Hi, @iileshii , @adolfo-novo

did adding work items ever work for you and just recently stopped working? Maybe the API changed a bit.

Couple you please provide the following Details:
- which worklog viewer version are you using?
- which youtrack version are you using it with?

**Comment by pbauerochse** [comment]
@batihu @iileshii could you please try the 2.7.4 version.

**Comment by adolfo-novo** [comment]
@pbauerochse . Working like a charm!!!!... Thanks!!

**Comment by batihu** [comment]
sorry .....I was buried in work 
U R awesome ...it works perfectly...thxalot
