### ISSUE TITLE
Show Short list my work items for Issue

### ISSUE THREAD

**Issue by adolfo-novo** [pbauerochse/youtrack-worklog-viewer#46]
It will be super useful to have a new item in the contextual menu for a certain task in Ownworklogs where popup a window with a shor list of your own workitems with their descriptions and type

**Comment by pbauerochse** [comment]
Hi @adolfo-novo ,

sorry for the late answer. My notification settings seem to be a bit off. When you hover over the cell with your mouse you should get a popup with your work entries for that issue on that particular date. Is that, what you were looking for?

![image](https://github.com/pbauerochse/youtrack-worklog-viewer/assets/1038095/6e69e764-40c8-4d6f-a65f-9ae7f6cd10c4)

**Comment by adolfo-novo** [comment]
Oh yes... sorry for not updating the comment. I didn´t see in that moment . Thanks a lot for your response

**Comment by adolfo-novo** [comment]
Closed by Author
